/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.32
 * Generated at: 2018-08-10 07:46:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.userReview;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class userReviewView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/views/userReview/../../header.jsp", Long.valueOf(1533477126000L));
    _jspx_dependants.put("/views/userReview/../../footer.jsp", Long.valueOf(1533706591088L));
    _jspx_dependants.put("/views/userReview/../../head.jsp", Long.valueOf(1533876049388L));
    _jspx_dependants.put("/views/userReview/../../end.jsp", Long.valueOf(1533202554000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no\" />\r\n");
      out.write("<meta name=\"format-detection\" content=\"telephone=no\" />\r\n");
      out.write("<meta name=\"apple-mobile-web-app-capable\" content=\"yes\" />\r\n");
      out.write("<meta name=\"apple-mobile-web-app-status-bar-style\" content=\"black\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.2.0/css/all.css\" integrity=\"sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ\" crossorigin=\"anonymous\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/mimi/resources/css/bootstrap.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"/mimi/resources/js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/mimi/resources/css/admin-review-thema.css?ver=8\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- 바디 태그 시작 -->\r\n");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>MIMI</title>\r\n");
      out.write("<!-- 상단에 노출되서 주석처리.. <title>header</title> -->\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\t\r\n");
      out.write("\tbody {\r\n");
      out.write("\t\tpadding-top: 120px;\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#mainNav > a{ \r\n");
      out.write("\t\tdisplay: inline-block; \r\n");
      out.write("\t} \r\n");
      out.write("\t\r\n");
      out.write("\t/*메뉴 묶음 박스*/\r\n");
      out.write("\t#mini-menu-box{\r\n");
      out.write("\t\tposition:absolute;\r\n");
      out.write("\t\ttop:26px;\r\n");
      out.write("\t\tright: 100px;\r\n");
      out.write("\t\twidth:50px;\r\n");
      out.write("\t\theight:50px;\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("/* \t\r\n");
      out.write("\t#mini-menu-box > div#menu-box-btn{\r\n");
      out.write("\t\tposition:absolute;\r\n");
      out.write("\t\ttop: 0px;\t\r\n");
      out.write("\t\tleft:0%;\r\n");
      out.write("\t\tfont-size: 50px;\r\n");
      out.write("\t\tcolor: #666;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write(" */\t\t\r\n");
      out.write(" \r\n");
      out.write(" \t/* 크기, 색상, 위치 수정 */\r\n");
      out.write("\t#mini-menu-box > div#menu-box-btn{\r\n");
      out.write("\t\tposition:absolute;\r\n");
      out.write("\t\ttop: 5px;\t\r\n");
      out.write("\t\tleft:10%;\r\n");
      out.write("\t\tfont-size: 40px;\r\n");
      out.write("\t\tcolor: #888;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t/*비회원 메뉴 박스*/\r\n");
      out.write("\t.menu-box \r\n");
      out.write("\t{\r\n");
      out.write("\t\tdisplay : none;\r\n");
      out.write("\t\ttop: 58pt;\r\n");
      out.write("\t\tright:-25pt;\r\n");
      out.write("\t\tposition: absolute;\r\n");
      out.write("\t\twidth: 260px;\r\n");
      out.write("\t\theight: 370px;\r\n");
      out.write("\t\tpadding: 10px;\r\n");
      out.write("\t\tbackground: white;\r\n");
      out.write("\t\t-webkit-border-radius: 0px;\r\n");
      out.write("\t\t-moz-border-radius: 0px;\r\n");
      out.write("\t\tborder-radius: 0px;\r\n");
      out.write("\t\tborder: #000000 solid 1px;\r\n");
      out.write("\t\tbox-shadow:0 5px 20px rgba(0, 0, 0, 0.8);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t.menu-box:after \r\n");
      out.write("\t{\r\n");
      out.write("\t\tcontent: '';\r\n");
      out.write("\t\tposition: absolute;\r\n");
      out.write("\t\tborder-style: solid; \r\n");
      out.write("\t\tborder-width: 0 16px 20px;\r\n");
      out.write("\t\tborder-color: white transparent;\r\n");
      out.write("\t\tdisplay: block;\r\n");
      out.write("\t\twidth: 0;\r\n");
      out.write("\t\tz-index: 1;\r\n");
      out.write("\t\ttop: -20px;\r\n");
      out.write("\t\tleft: 185px;\r\n");
      out.write("\t\t\r\n");
      out.write("\t} \r\n");
      out.write("\r\n");
      out.write("\t.menu-box:before \r\n");
      out.write("\t{\r\n");
      out.write("\t\tcontent: '';\r\n");
      out.write("\t\tposition: absolute;\r\n");
      out.write("\t\tborder-style: solid;\r\n");
      out.write("\t\tborder-width: 0 16px 20px;\r\n");
      out.write("\t\tborder-color: #000000 transparent;\r\n");
      out.write("\t\tdisplay: block;\r\n");
      out.write("\t\twidth: 0;\r\n");
      out.write("\t\tz-index: 0;\r\n");
      out.write("\t\ttop: -21px;\r\n");
      out.write("\t\tleft: 185px;\r\n");
      out.write("\t\t \r\n");
      out.write("\t}   \r\n");
      out.write("\t\r\n");
      out.write("\t@media (max-width:390px){\r\n");
      out.write("\t\t#mini-menu-box{\r\n");
      out.write("\t\t\t/* display:relative; */\r\n");
      out.write("\t\t\tleft : 200px!important\r\n");
      out.write("\t\t}\r\n");
      out.write("\t} \r\n");
      out.write("\t@media (max-width:355px){\r\n");
      out.write("\t\t#song-navbar-toggle{\r\n");
      out.write("\t\t\tleft:90px;\r\n");
      out.write("\t\t\twidth:75px;\r\n");
      out.write("\t\t}\t\r\n");
      out.write("\t}\r\n");
      out.write("\t@media (max-width: 992px){\r\n");
      out.write("\t\t.mini-li-box{\r\n");
      out.write("\t\t\tdisplay: inline-block;\r\n");
      out.write("\t\t\tfloat: none;\r\n");
      out.write("\t\t} \r\n");
      out.write("\t\t#bs-example-navbar-collapse-1{ /*헤더 네비 가운데 정렬*/\r\n");
      out.write("\t\t\ttext-align: center; \r\n");
      out.write("\t\t\r\n");
      out.write("\t\t} \r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.mini-li-box{\r\n");
      out.write("\t\tdisplay: inline-block;\r\n");
      out.write("\t\tfloat: none;\r\n");
      out.write("\t} \r\n");
      out.write("\t#bs-example-navbar-collapse-1{ /*헤더 네비 가운데 정렬*/\r\n");
      out.write("\t\ttext-align: center; \r\n");
      out.write("\t\t\r\n");
      out.write("\t} \r\n");
      out.write("\t\r\n");
      out.write("\t#menu-box-btn:hover {\r\n");
      out.write("\t\tcolor: #ccc!important;\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t@media (min-width: 993px){ \r\n");
      out.write("\t\t#bs-example-navbar-collapse-1{\r\n");
      out.write("\t\t\ttop:0px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\t\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Navigation -->\r\n");
      out.write("    <nav id=\"mainNav\" class=\"navbar navbar-default navbar-fixed-top header-and-footer\">\r\n");
      out.write("        \r\n");
      out.write("        <a href=\"/mimi/index.jsp\"><img style=\"position: absolute; max-height:50px;max-width:200px; left:5%; top:24px; z-index: 1;\" src=\"/mimi/resources/images/logo/mm_logo_onlytext_red.svg\"></a>\r\n");
      out.write("        <div class=\"container\" style=\"position:relative; top:-10px;\">\r\n");
      out.write("            <!-- Brand and toggle get grouped for better mobile display -->\r\n");
      out.write("           \r\n");
      out.write("            <div class=\"navbar-header\">\r\n");
      out.write("            \r\n");
      out.write("                <button id=\"song-navbar-toggle\" type=\"button\"  class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#bs-example-navbar-collapse-1\">\r\n");
      out.write("                    <span class=\"sr-only\">Toggle navigation</span> Menu <i class=\"fa fa-bars\"></i>\r\n");
      out.write("                </button>\r\n");
      out.write("                \r\n");
      out.write("                <div style=\"height:50px;width:0px;\"></div><!--세로 크기 줄어들지 않게 하기 위한 투명 박스 -->\r\n");
      out.write("            </div>\r\n");
      out.write("\t\r\n");
      out.write("            <!-- Collect the nav links, forms, and other content for toggling -->\r\n");
      out.write("            <div class=\"collapse navbar-collapse\" id=\"bs-example-navbar-collapse-1\" >\r\n");
      out.write("                <ul class=\"nav navbar-nav mini-li-box\">\r\n");
      out.write("                    <li class=\"hidden\">\r\n");
      out.write("                        <a href=\"#page-top\"></a>\r\n");
      out.write("                    </li> \r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"/mimi/views/notice/noticeList.jsp\">공지사항</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"/mimi/views/board/adminReview.jsp\">MIMI 리뷰</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"/mimi/views/bestReview/bestReviewList.jsp\">Best리뷰</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"/mimi/views/userReview/userReviewList.jsp\">유저리뷰</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"/mimi/views/board/nearShop.jsp\">주변매장</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"/mimi/views/member/customer.jsp\">고객센터</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"/mimi/views/intro/information.jsp\">사이트소개</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- /.navbar-collapse -->\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- /.container-fluid -->\r\n");
      out.write("        <nav id=\"mini-menu-box\">\r\n");
      out.write("\t\t\t<div id=\"menu-box-btn\" class=\"far fa-user-circle\" aria-hidden=\"true\"></div>\r\n");
      out.write("\t\t\t<!-- 로그 아웃상태에서 메뉴 버튼 누를시 -->\r\n");
      out.write("\t\t\t<div class=\"menu-box\">\r\n");
      out.write("\t\t\t\t<h3 align=\"center\">로그인 및 회원가입</h3>\r\n");
      out.write("\t\t\t\t<hr style=\"border: thin 1px black;\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<form role=\"form\">\r\n");
      out.write("            \t\t<div class=\"form-group\" align=\"center\">\r\n");
      out.write("              \t\t\t<input type=\"email\" class=\"form-control\" id=\"InputEmail\" style=\"width:150pt;\" placeholder=\"아이디 입력\">\r\n");
      out.write("              \t\t</div>\r\n");
      out.write("              \t\t<div class=\"form-group\" align=\"center\">\t\r\n");
      out.write("              \t\t\t<input type=\"email\" class=\"form-control\" id=\"InputEmail\" style=\"width:150pt;\" placeholder=\"비밀번호 입력\">\r\n");
      out.write("              \t\t</div>\t\r\n");
      out.write("              \t\t<div class=\"form-group\">\r\n");
      out.write("              \t\t\t<p class=\"help-block\" align=\"right\" style=\"color:#d9534f; font-size:12px;\"><a href=\"#\">아이디/비밀번호 찾기</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</p>\r\n");
      out.write("              \t\t</div>\r\n");
      out.write("              \t\t<div class=\"form-group\" align=\"center\">\t\r\n");
      out.write("              \t\t\t<button type=\"submit\" class=\"btn btn-info\" style=\"width:80%; margin:0px; outline: none;\">로그인&nbsp;<i class=\"fa fa-check spaceLeft\"></i></button>\t\t\r\n");
      out.write("            \t\t</div>\t\r\n");
      out.write("            \t</form>\t\r\n");
      out.write("            \t<hr style=\"margin: 0px 1px 10px 1px;\">\t\t\r\n");
      out.write("            \t<div align=\"center\">\t\r\n");
      out.write("              \t\t<a href=\"/mimi/views/member/memberEnroll.jsp\"><button type=\"button\" class=\"btn btn-success\" style=\"width:80%; outline: none;\">회원가입&nbsp;<i class=\"fa fa-check spaceLeft\"></i></button></a>\t\t\r\n");
      out.write("            \t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("    </nav>\r\n");
      out.write("    \r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("\t\t$(function(){\r\n");
      out.write("\t\t\t$(document).on(\"mouseover\", \"#menu-box-btn\", function(){\r\n");
      out.write("\t\t\t\t$(\"#menu-box-btn\").css(\"cursor\", \"pointer\");\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t$(document).on(\"click\", \"#menu-box-btn\", function(){\r\n");
      out.write("\t\t\t\tif($(\".menu-box\").css(\"display\") === \"none\"){\r\n");
      out.write("\t\t\t\t\t$(\".menu-box\").slideDown(\"slow\", function() {\t\t\t\r\n");
      out.write("\t\t\t\t\t});\t\t\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\telse{\r\n");
      out.write("\t\t\t\t\t$(\".menu-box\").slideUp(\"slow\", function() {\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- ---------------------- -->\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/clipboard.js/1.5.3/clipboard.min.js\"></script>\r\n");
      out.write("<script src=\"/mimi/resources/js/kakao.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("#text_context {\r\n");
      out.write("\tfont-family: \"Helvetica Nene\", Helvetica, Arial, sans-serif;\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("\tline-height: 1.42857143;\r\n");
      out.write("\tcolor: #333;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#good_qta {\r\n");
      out.write("\tfont-family: \"Helvetica Nene\", Helvetica, Arial, sans-serif;\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("\tline-height: 1.42857143;\r\n");
      out.write("\tcolor: #333;\r\n");
      out.write("\tbackground-color: #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#comment {\r\n");
      out.write("\tfont-family: \"Helvetica Nene\", Helvetica, Arial, sans-serif;\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("\tline-height: 1.42857143;\r\n");
      out.write("\tcolor: #333;\r\n");
      out.write("\tbackground-color: #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#table-css2 th{\r\n");
      out.write("\tbackground:#fff;\r\n");
      out.write("\tfont-size: 13px;\r\n");
      out.write("\tcolor: #666;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#table-css2 td{\r\n");
      out.write("\ttext-align:left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".margin5{\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tmargin: 15px 15px 10px 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tnew Clipboard('.copyBtn', {text: function() {\r\n");
      out.write("\t\t\talert(\"클립보드에 복사되었습니다.\");\r\n");
      out.write("\t\t    return document.location.href;\r\n");
      out.write("\t\t  }\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});//onload\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<!-- <title>유저리뷰보기</title> -->\r\n");
      out.write("<div class=\"container\" style=\"width:1150px;\">\r\n");
      out.write("\t<h3>유저리뷰</h3>\r\n");
      out.write("\t<div id=\"inner\">\r\n");
      out.write("\t\t<table class=\"table table-borderless\" id=\"table-css2\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th width=\"12%\">No.9999</th>\r\n");
      out.write("\t\t\t\t<th width=\"*\" style=\"text-align:left;\">제목제목제목제목제목제목제목제목제목</th>\r\n");
      out.write("\t\t\t\t<th width=\"28%\">\r\n");
      out.write("\t\t\t\t<i class=\"fas fa-pen\"></i>글쓴이&nbsp;Lv.1\r\n");
      out.write("\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<i class=\"far fa-eye\"></i>99999\r\n");
      out.write("\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<i class=\"far fa-calendar\"></i>07-22</th>\r\n");
      out.write("\t\t\t\t<th width=\"8%\"><button type=\"button\" class=\"btn btn-default btn-lg\" id=\"favorites\" onclick=\"imgToggle()\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"glyphicon glyphicon-star\" aria-hidden=\"true\" style=\"color: yellow\"></span>\r\n");
      out.write("\t\t\t\t\t</button></th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>카테고리</th>\r\n");
      out.write("\t\t\t\t<td id=\"text_category\">\r\n");
      out.write("\t\t\t\t\t<div class=\"btn-toolbar\" role=\"toolbar\" aria-label=\"버튼 그룹이 있는 툴바\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"btn-group mr-2\" role=\"group\" aria-label=\"첫번째 그룹\">\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\" class=\"btn\" style=\"width: 110px\">카페</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"btn-group mr-2\" role=\"group\" aria-label=\"두번째 그룹\">\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\" class=\"btn\" style=\"width: 110px\">패스트푸드</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"btn-group mr-2\" role=\"group\" aria-label=\"첫번째 그룹\">\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\" class=\"btn\" style=\"width: 110px\">한식</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"btn-group mr-2\" role=\"group\" aria-label=\"두번째 그룹\">\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\" class=\"btn\" style=\"width: 110px\">4</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<br> <br>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"btn-group mr-2\" role=\"group\" aria-label=\"첫번째 그룹\">\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\" class=\"btn\" style=\"width: 110px\">5</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"btn-group mr-2\" role=\"group\" aria-label=\"두번째 그룹\">\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\" class=\"btn\" style=\"width: 110px\">6</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"btn-group mr-2\" role=\"group\" aria-label=\"첫번째 그룹\">\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\" class=\"btn\" style=\"width: 110px\">7</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"btn-group mr-2\" role=\"group\" aria-label=\"두번째 그룹\">\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\" class=\"btn\" style=\"width: 110px\">8</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td style=\"width: 300px; align:center;\" rowspan=\"4\" colspan=\"2\"><img\r\n");
      out.write("\t\t\t\t\tsrc=\"/mimi/resources/images/userReview/map.jpg\" width=100%\r\n");
      out.write("\t\t\t\t\theight=300></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>매장명</th>\r\n");
      out.write("\t\t\t\t<td>미미카페</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>연락처</th>\r\n");
      out.write("\t\t\t\t<td>02-123-4567</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>매장 주소</th>\r\n");
      out.write("\t\t\t\t<td>서울시 00구 00동 232-23</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<hr class=\"margin2\">\r\n");
      out.write("\t<div style=\"margin:20px;\">\r\n");
      out.write("\t<p id=\"text_context\">\r\n");
      out.write("\t\t숙소에서 추천받아 방문하였습니다.<br> 주민분들이 많이 찾는 곳이라고 합니다.<br> 목살 2 먹고 고기\r\n");
      out.write("\t\t질과 맛이 뛰어나 삼겹살도 1인분 추가 주문하였습니다.<br> 우선 모든 고기 한면에 칼집이 있으며<br>\r\n");
      out.write("\t\t두께가 참 두툼하니 먹음직스럽습니다.<br> 고기는 축협 고기라 합니다.<br> 밑반찬으로 파절이와\r\n");
      out.write("\t\t분홍소세지 등이 나오며,<br> 공깃밥에는 된장찌개가 함께 나옵니다.<br> 된장찌개가 평범하진 않게\r\n");
      out.write("\t\t맛있습니다.<br> 고추장과 된장을 좀 섞은 맛입니다.<br> 무엇보다 고기가 매우 좋아서<br>\r\n");
      out.write("\t\t흑돼지던 아니던 상관 없었습니다.<br>\r\n");
      out.write("\t</p>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<hr>\r\n");
      out.write("\t<div style=\"text-align: right;\">\r\n");
      out.write("\t<button class=\"btn\" id=\"btn\" type=\"submit\" style=\"background:#fff; padding:1px; outline: none;\" title=\"페이스북에 공유하기\" onclick=\"window.open('http://www.facebook.com/sharer.php?u=hjl822.cafe24.com')\"><img class=\"btn-img\" width=40px src=\"/mimi/resources/images/icon/icon_facebook.png\"></button>\r\n");
      out.write("\t<button class=\"btn\" id=\"btn\" type=\"submit\" style=\"background:#fff; padding:1px; outline: none;\" title=\"트위터에 공유하기\" onclick=\"window.open('https://twitter.com/intent/tweet?text=리뷰제목&url=리뷰주소')\"><img class=\"btn-img\" width=40px src=\"/mimi/resources/images/icon/icon_twitter.png\"></button>\r\n");
      out.write("\t<button class=\"btn\" id=\"btn\" type=\"submit\" style=\"background:#fff; padding:1px; outline: none;\" title=\"라인에 공유하기\" onclick=\"window.open('http://line.naver.jp/R/msg/text/')\"><img class=\"btn-img\" width=40px src=\"/mimi/resources/images/icon/icon_line.png\"></button>\r\n");
      out.write("\t<!-- <button class=\"btn\" id=\"btn\" type=\"submit\" style=\"background:#fff; padding:1px; outline: none;\" title=\"카카오톡에 공유하기\"><img width=40px src=\"/mimi/resources/images/icon/icon_kakao.png\"></button> -->\r\n");
      out.write("\t<a id=\"kakaoLink-btn\" href=\"javascript:;\"><img src=\"/mimi/resources/images/icon/icon_kakao.png\" width=40px title=\"카카오톡에 공유하기\"></a>\r\n");
      out.write("\t<button class=\"btn copyBtn\" id=\"kakaoLink-btn\" type=\"submit\" style=\"background:#fff; padding:1px; outline: none;\" title=\"url 복사하기\"><img class=\"btn-img\" width=40px src=\"/mimi/resources/images/icon/icon_copy.png\"></button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<hr>\r\n");
      out.write("\t<div id=\"image_l\" style=\"text-align: center;\">\r\n");
      out.write("\t\t<img src=\"/mimi/resources/images/userReview/s_1.jpg\" width=400\r\n");
      out.write("\t\t\theight=300><br>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<div id=\"image_s\" style=\"text-align: center;\">\r\n");
      out.write("\t\t<img src=\"/mimi/resources/images/userReview/s_1.jpg\" width=150\r\n");
      out.write("\t\t\theight=100> <img\r\n");
      out.write("\t\t\tsrc=\"/mimi/resources/images/userReview/s_3.jpg\" width=150 height=100>\r\n");
      out.write("\t\t<img src=\"/mimi/resources/images/userReview/s_1.jpg\" width=150\r\n");
      out.write("\t\t\theight=100>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<hr>\r\n");
      out.write("\t<div style=\"text-align: center;\">\r\n");
      out.write("\t\t\t<img class=\"btn-img\"\r\n");
      out.write("\t\t\t\tsrc=\"/mimi/resources/images/icon/icon_thumb_up.png\" width=100\r\n");
      out.write("\t\t\t\t onclick=\"#\">\r\n");
      out.write("\t\t<p id=\"good_qta\">111</p>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- comment -->\r\n");
      out.write("\t<div style=\"text-align: center;\">\r\n");
      out.write("\t\t<!-- 기존 댓글 -->\r\n");
      out.write("\t\t<table class=\"table table-borderless\" style=\"width:100%\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><table id=\"comment\" style=\"width:100%\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td style=\"width: 40px\"><img src=\"/mimi/resources/images/icon/icon_human.ico\" width=40 height=40></td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"text-left\">&nbsp;user01 <span style=\"font-size: 8px\">&nbsp;&nbsp;2018-08-02 00:02:25</span></td>\r\n");
      out.write("\t\t\t\t\t\t<td style=\"width: 50px\" class=\"text-center\"><a href=\"/mimi/views/userReview/userReviewList.jsp\">수정</a></td>\r\n");
      out.write("\t\t\t\t\t\t<td style=\"width: 50px\" class=\"text-center\"><a href=\"#\">삭제</a></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr><!-- 댓글 본문 -->\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"4\" class=\"text-left\"><div class=\"margin5\">추천요11 1111111 1111?? 추천요11 1111111 1111?? 추천요11 1111111 1111?? 추천요11 1111111 1111?? 추천요11 1111111 1111?? 추천요11 1111111 1111?? 추천요11 1111111 1111?? 추천요11 1111111 1111?? 추천요11 1111111 1111?? 추천요11 1111111 1111?? ??fffffffffffffffff아니 왤케 끝없이 늘어나??????</div></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><table id=\"comment\" style=\"width:100%\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td style=\"width: 40px\"><img src=\"/mimi/resources/images/icon/icon_human.ico\" width=40 height=40></td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"text-left\">&nbsp;user01 <span style=\"font-size: 8px\">&nbsp;&nbsp;2018-08-02 00:02:25</span></td>\r\n");
      out.write("\t\t\t\t\t\t<td style=\"width: 50px\" class=\"text-center\"><a href=\"/mimi/views/userReview/userReviewList.jsp\">수정</a></td>\r\n");
      out.write("\t\t\t\t\t\t<td style=\"width: 50px\" class=\"text-center\"><a href=\"#\">삭제</a></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr><!-- 댓글 본문 -->\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"4\" class=\"text-left\"><div class=\"margin5\">추천요11 1111111 1111?? 추천요11 1111111 1111?? 추천요11 1111111 1111?? 추천요11 1111111 1111?? 추천요11 1111111 1111?? 추천요11 1111111 1111?? 추천요11 1111111 1111?? 추천요11 1111111 1111?? 추천요11 1111111 1111?? 추천요11 1111111 1111?? ??fffffffffffffffff아니 왤케 끝없이 늘어나??????</div></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><table id=\"comment\" style=\"width:100%\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td style=\"width: 40px\"><img src=\"/mimi/resources/images/icon/icon_human.ico\" width=40 height=40></td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"text-left\">&nbsp;user01 <span style=\"font-size: 8px\">&nbsp;&nbsp;2018-08-02 00:02:25</span></td>\r\n");
      out.write("\t\t\t\t\t\t<td style=\"width: 50px\" class=\"text-center\"><a href=\"/mimi/views/userReview/userReviewList.jsp\">수정</a></td>\r\n");
      out.write("\t\t\t\t\t\t<td style=\"width: 50px\" class=\"text-center\"><a href=\"#\">삭제</a></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr><!-- 댓글 본문 -->\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"4\" class=\"text-left\"><div class=\"margin5\">추천요11 1111111 1111?? 추천요11 1111111 1111?? 추천요11 1111111 1111?? 추천요11 1111111 1111?? 추천요11 1111111 1111?? 추천요11 1111111 1111?? 추천요11 1111111 1111?? 추천요11 1111111 1111?? 추천요11 1111111 1111?? 추천요11 1111111 1111?? ??fffffffffffffffff아니 왤케 끝없이 늘어나??????</div></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><table id=\"comment\" style=\"width:100%\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td style=\"width: 40px\"><img src=\"/mimi/resources/images/icon/icon_human.ico\" width=40 height=40></td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"text-left\">&nbsp;user01 <span style=\"font-size: 8px\">&nbsp;&nbsp;2018-08-02 00:02:25</span></td>\r\n");
      out.write("\t\t\t\t\t\t<td style=\"width: 50px\" class=\"text-center\"><a href=\"/mimi/views/userReview/userReviewList.jsp\">수정</a></td>\r\n");
      out.write("\t\t\t\t\t\t<td style=\"width: 50px\" class=\"text-center\"><a href=\"#\">삭제</a></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr><!-- 댓글 본문 -->\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"4\" class=\"text-left\"><div class=\"margin5\">추천요11 1111111 1111?? 추천요11 1111111 1111?? 추천요11 1111111 1111?? 추천요11 1111111 1111?? 추천요11 1111111 1111?? 추천요11 1111111 1111?? 추천요11 1111111 1111?? 추천요11 1111111 1111?? 추천요11 1111111 1111?? 추천요11 1111111 1111?? ??fffffffffffffffff아니 왤케 끝없이 늘어나??????</div></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><table id=\"comment\" style=\"width:100%\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td style=\"width: 40px\"><img src=\"/mimi/resources/images/icon/icon_human.ico\" width=40 height=40></td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"text-left\">&nbsp;user01 <span style=\"font-size: 8px\">&nbsp;&nbsp;2018-08-02 00:02:25</span></td>\r\n");
      out.write("\t\t\t\t\t\t<td style=\"width: 50px\" class=\"text-center\"><a href=\"/mimi/views/userReview/userReviewList.jsp\">수정</a></td>\r\n");
      out.write("\t\t\t\t\t\t<td style=\"width: 50px\" class=\"text-center\"><a href=\"#\">삭제</a></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr><!-- 댓글 본문 -->\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"4\" class=\"text-left\"><div class=\"margin5\">추천요11 1111111 1111?? 추천요11 1111111 1111?? 추천요11 1111111 1111?? 추천요11 1111111 1111?? 추천요11 1111111 1111?? 추천요11 1111111 1111?? 추천요11 1111111 1111?? 추천요11 1111111 1111?? 추천요11 1111111 1111?? 추천요11 1111111 1111?? ??fffffffffffffffff아니 왤케 끝없이 늘어나??????</div></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><table id=\"comment\" style=\"width:100%\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td style=\"width: 40px\"><img src=\"/mimi/resources/images/icon/icon_human.ico\" width=40 height=40></td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"text-left\">&nbsp;user01 <span style=\"font-size: 8px\">&nbsp;&nbsp;2018-08-02 00:02:25</span></td>\r\n");
      out.write("\t\t\t\t\t\t<td style=\"width: 50px\" class=\"text-center\"><a href=\"/mimi/views/userReview/userReviewList.jsp\">수정</a></td>\r\n");
      out.write("\t\t\t\t\t\t<td style=\"width: 50px\" class=\"text-center\"><a href=\"#\">삭제</a></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr><!-- 댓글 본문 -->\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"4\" class=\"text-left\"><div class=\"margin5\">추천요11 1111111 1111?? 추천요11 1111111 1111?? 추천요11 1111111 1111?? 추천요11 1111111 1111?? 추천요11 1111111 1111?? 추천요11 1111111 1111?? 추천요11 1111111 1111?? 추천요11 1111111 1111?? 추천요11 1111111 1111?? 추천요11 1111111 1111?? ??fffffffffffffffff아니 왤케 끝없이 늘어나??????</div></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<hr class=\"margin2\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- 댓글 작성부분 -->\r\n");
      out.write("\t\t<form>\r\n");
      out.write("\t\t<table style=\"width:100%;\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width=\"15%\"><img src=\"/mimi/resources/images/icon/icon_human.ico\" width=40\r\n");
      out.write("\t\t\t\theight=40>&nbsp;&nbsp;<label>user03</label></td>\r\n");
      out.write("\t\t\t\t<td width=\"*\"><textarea style=\"width: 100%;\" rows=\"3\" id=\"texta_content\"></textarea></td>\r\n");
      out.write("\t\t\t\t<td width=\"8%\"><button type=\"submit\" class=\"btn btn-default\" style=\"outline: none;\">등록</button></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t<!-- /댓글 작성부분 -->\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<hr>\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\t\t<div class=\"col-xs-6 text-left\">\r\n");
      out.write("\t\t\t<input type=\"button\" class=\"btn btn-default\"\r\n");
      out.write("\t\t\t\tonClick=\"location.href='/mimi/views/userReview/userReviewList.jsp'\"\r\n");
      out.write("\t\t\t\tvalue=\"목록\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-xs-6 text-right\">\r\n");
      out.write("\t\t\t<input type=\"submit\" class=\"btn btn-default\" value=\"수정\" style=\"outline: none;\"> <input\r\n");
      out.write("\t\t\t\ttype=\"submit\" class=\"btn btn-default\" value=\"삭제\" style=\"outline: none;\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<br>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- 카톡공유용 -->\r\n");
      out.write("<script type='text/javascript'>\r\n");
      out.write("\tKakao.init('86bba96268a8b3515e937b123d69953a'); //kakao 키번호\r\n");
      out.write("\tvar url = document.location.href;\r\n");
      out.write("    \r\n");
      out.write("    Kakao.Link.createDefaultButton({\r\n");
      out.write("      container: '#kakaoLink-btn',\r\n");
      out.write("      objectType: 'feed',\r\n");
      out.write("      content: {\r\n");
      out.write("        title: '제목',\r\n");
      out.write("        description: '내용..........',\r\n");
      out.write("        imageUrl: 'http://hjl822.cafe24.com/mimi/resources/images/main/img3.jpg',\t//이미지주소..http로 시작해야 뜸 X절대경로,상대경로X\r\n");
      out.write("        link: {\r\n");
      out.write("          mobileWebUrl: 'url',\t//주소..url 가져다 쓰면되는데....웹서버에 올려야함\r\n");
      out.write("          webUrl: 'http://hjl822.cafe24.com/mimi/views/userReview/userReviewView.jsp'\r\n");
      out.write("        }\r\n");
      out.write("      },\r\n");
      out.write("      social: {\r\n");
      out.write("        likeCount: 286, //좋아요 수\r\n");
      out.write("        commentCount: 45, //댓글 수\r\n");
      out.write("        viewCount: 999\t//조회수\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- <title>Insert title here</title> -->\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t.header-and-footer{\r\n");
      out.write("\t\tpadding-top: 15px;\r\n");
      out.write("\t\tpadding-bottom: 15px; \r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t.custom-footer{\r\n");
      out.write("\tmin-width:1150px; /* 추가, 게시판 너비 맞춤*/\r\n");
      out.write("\t\tmargin-top: 50px;\r\n");
      out.write("\t\tmargin-bottom: 0px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.footer{\r\n");
      out.write("\t\t\r\n");
      out.write("\t\ttext-align:center;\r\n");
      out.write("\t\tmargin-top: 2px;\r\n");
      out.write("\t\tmargin-bottom: 2px;\r\n");
      out.write("\t\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\t<nav class=\"navbar navbar-default custom-footer header-and-footer\">\r\n");
      out.write("  \t\t<div class=\"container\">\r\n");
      out.write("   \t\t\t<p class=\"footer\">이용약관 개인정보처리방침 책임의 한계와 법적고지 고객센터</p>\r\n");
      out.write("   \t\t\t<p class=\"footer\">tel : 010-0000-0000 fax: 000-0000-0000</p>\r\n");
      out.write("   \t\t\t<p class=\"footer\">Copyright MIMI Corp.All Rights Reserved.</p>\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("\t</nav>");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/mimi/resources/js/bootstrap.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/mimi/resources/js/kakao.min.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("<!-- 바디 태그 끝 -->\r\n");
      out.write("</html>\t");
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
