/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.32
 * Generated at: 2018-08-21 07:13:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class NewFile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t function FaqToggleDetail ( id ){\r\n");
      out.write("\t\tvar latestToggleObj = null;\r\n");
      out.write("\t\tvar oObj = document.getElementById( id );\t\r\n");
      out.write("\r\n");
      out.write("\t\tif( this.latestToggleObj != null ){\r\n");
      out.write("\t\t\tthis.latestToggleObj.className = (this.latestToggleObj.className + \" none\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif( this.latestToggleObj == oObj ){\r\n");
      out.write("\t\t\tthis.latestToggleObj = null;\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tthis.latestToggleObj = null;\r\n");
      out.write("\r\n");
      out.write("\t\tif( oObj.className.indexOf( \"none\" ) != -1 ){\r\n");
      out.write("\t\t\toObj.className = oObj.className.replace( \"none\", \"\" );\t\t\t\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\toObj.className = (oObj.className + \" none\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tthis.latestToggleObj = oObj;\r\n");
      out.write("\t }\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write(".none{ display:none; }\r\n");
      out.write(".pointer{ cursor:pointer; }\r\n");
      out.write("</style>\r\n");
      out.write("<p>질문게시판입니다.</p>\r\n");
      out.write("<table cellspacing=\"0\" class=\"article-list\">\r\n");
      out.write("<col width=\"30px\">\r\n");
      out.write("<col>\r\n");
      out.write("<col width=\"60px\" >\r\n");
      out.write("<col width=\"80px\" >\r\n");
      out.write("<col width=\"50px\" >\r\n");
      out.write("<col width=\"50px\" >\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("<th>No2</th>\r\n");
      out.write("<th>제 목</th>\r\n");
      out.write("<th>작성자</th>\r\n");
      out.write("<th>작성일</th>\r\n");
      out.write("<th>조회</th>\r\n");
      out.write("<th>추천</th>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr align=\"center\" class=\"pointer\" onclick=\"FaqToggleDetail( 'row_1' )\">\r\n");
      out.write("\t<td>1</td>\r\n");
      out.write("\t<td>\r\n");
      out.write("\t<span id=\"td_row_1\">'javascript typeof'에 해당되는 글 1건</span></td>\r\n");
      out.write("\t<td>게시판 만들기</td>\r\n");
      out.write("\t<td>2009/12/04</td>\r\n");
      out.write("\t<td>2321</td>\r\n");
      out.write("\t<td>123</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr class=\"none\" id=\"row_1\">\r\n");
      out.write("\t<td colspan=\"6\" style=\"border:1px solid #000000;\">\r\n");
      out.write("\t'javascript typeof'에 해당되는 글 1건. 2009/12/04 typeof · WEB/자바스크립트2009/12/04 12:41 ... FAQ (검색결과: 건) ... 이전 1 다음» ... 계층형 게시판 만들기 (9) ...\r\n");
      out.write("\t<td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr align=\"center\" class=\"pointer\" onclick=\"FaqToggleDetail( 'row_2' )\">\r\n");
      out.write("\t<td>2</td>\r\n");
      out.write("\t<td>\r\n");
      out.write("\t<span id=\"td_row_2\">PHPSchool 의 Tip&Tech 란에서 퍼온것을 미리</span></td>\r\n");
      out.write("\t<td>URL 숨기기</td>\r\n");
      out.write("\t<td>2009/12/04</td>\r\n");
      out.write("\t<td>2321</td>\r\n");
      out.write("\t<td>123</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr class=\"none\" id=\"row_2\">\r\n");
      out.write("\t<td colspan=\"6\" style=\"border:1px solid #000000;\">\r\n");
      out.write("박스의 비밀. 이 글은 PHPSchool 의 Tip&Tech 란에서 퍼온것을 미리 밝혀둡니다. ... 웹플레이어의 경우 자바스크립트로 현재 플레이되는 곡에 대한 정보를 ..... URL 숨기기용 플레이어에 곡전달하는 파일 샘플 \r\n");
      out.write("\t<td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr align=\"center\" class=\"pointer\" onclick=\"FaqToggleDetail( 'row_3' )\">\r\n");
      out.write("\t<td>3</td>\r\n");
      out.write("\t<td>\r\n");
      out.write("\t<span id=\"td_row_3\">Web Controls 1.0에도 집중</span></td>\r\n");
      out.write("\t<td>URL 숨기기</td>\r\n");
      out.write("\t<td>2009/12/04</td>\r\n");
      out.write("\t<td>2321</td>\r\n");
      out.write("\t<td>123</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr class=\"none\" id=\"row_3\">\r\n");
      out.write("\t<td colspan=\"6\" style=\"border:1px solid #000000;\">\r\n");
      out.write("\t이전에는 Web Forms 2.0과 Web Controls 1.0에도 집중했었습니다. .... 사양은 사용자-에이전트-특화요소를 강조하거나 숨기는 등 변경하는 .... 많은 기능은 자바스크립트를 사용하여 대체하여 구현 12할 수 ..... 클보 게시판 최신글\r\n");
      out.write("\t<td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr align=\"center\" class=\"pointer\" onclick=\"FaqToggleDetail( 'row_4' )\">\r\n");
      out.write("\t<td>4</td>\r\n");
      out.write("\t<td>\r\n");
      out.write("\t<span id=\"td_row_4\">JAVA프로그래머를 위해</span></td>\r\n");
      out.write("\t<td>URL 숨기기</td>\r\n");
      out.write("\t<td>2009/12/04</td>\r\n");
      out.write("\t<td>2321</td>\r\n");
      out.write("\t<td>123</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr class=\"none\" id=\"row_4\">\r\n");
      out.write("\t<td colspan=\"6\" style=\"border:1px solid #000000;\">\r\n");
      out.write("\t들어가는 글 :: \"시작하는 JAVA프로그래머를 위해\" (특히 비 전공자분들 ... 김상욱의 LIVECONNECTION :: 애플릿과 자바스크립트와의 통신강좌 ..... JSP FAQ\r\n");
      out.write("\t<td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("출처: http://hosting.websearch.kr/entry/javascript-Toggle-사용-FAQ-질문게시판-글목록과-내용-함께-보이게-하기 [웹호스팅정보 - 호스팅 프로그램 쇼핑몰 이미지 폰트 리뷰]");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
